spring.config.name=fossa-mini
spring.main.show-banner=false

# ??????
server.port=7824
server.servlet.context-path=/fossa/mini
server.servlet.session.timeout=1800s



# HTTP ????????
http.client.socketTimeout=10
http.client.connectionRequestTimeout=10
http.client.connectionTimeout=10
http.client.closeIdleConnections=30


# REDIS (RedisProperties)
spring.redis.host=yuni.fossa.top
spring.redis.password=fossayuni7788s
spring.redis.port=25176
spring.redis.index=0
spring.redis.pool.max-idle=200
spring.redis.pool.min-idle=10
spring.redis.pool.max-active=1000
spring.redis.pool.max-wait=5000
spring.redis.timeout=10000
# REDIS (RedisProperties)
fossa.redis.host=yuni.fossa.top
fossa.redis.password=fossayuni7788s
fossa.redis.port=25176
fossa.redis.index=0
fossa.redis.pool.max-idle=200
fossa.redis.pool.min-idle=10
fossa.redis.pool.max-active=1000
fossa.redis.pool.max-wait=5000
# ???????
wechat.appid=wx95ab971ffe17590e
wechat.secret=b5c316445a61594e7ce394311d8d930b
wechat.grant-type=authorization_code

mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.fossa.entity
# ???????????????? resultMap
mybatis.configuration.map-underscore-to-camel-case=true


upload.image.path=/data/upload
upload.image.domain=https://yuni.fossa.top

huita.cors.origins=https://yuni.fossa.top