#spring.datasource config
spring.datasource.name=fossa
spring.datasource.url=jdbc:mysql://10.2.0.7:52731/fossa?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true&allowMultiQueries=true&autoReconnect=true&socketTimeout=30000&connectTimeout=10000
spring.datasource.username=fossa
spring.datasource.password=Fossa@2026
spring.datasource.filters=stat
spring.datasource.maxActive=50
spring.datasource.initialSize=20
spring.datasource.maxWait=60000
spring.datasource.minIdle=20
spring.datasource.timeBetweenEvictionRunsMillis=60000
spring.datasource.minEvictableIdleTimeMillis=300000
spring.datasource.validationQuery=SELECT 'x'
spring.datasource.testWhileIdle=true
spring.datasource.testOnBorrow=false
spring.datasource.testOnReturn=false
spring.datasource.poolPreparedStatements=false
spring.datasource.maxOpenPreparedStatements=20
spring.datasource.slowSqlMillis=5000
spring.datasource.isLogSlowSql=true


#read spring.datasource config
spring.read.datasource.name=fossa
spring.read.datasource.url=jdbc:mysql://10.2.0.7:52731/fossa?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true&allowMultiQueries=true&autoReconnect=true&socketTimeout=30000&connectTimeout=10000
spring.read.datasource.username=fossa
spring.read.datasource.password=Fossa@2026
spring.read.datasource.filters=stat
spring.read.datasource.maxActive=50
spring.read.datasource.initialSize=20
spring.read.datasource.maxWait=60000
spring.read.datasource.minIdle=20
spring.read.datasource.timeBetweenEvictionRunsMillis=60000
spring.read.datasource.minEvictableIdleTimeMillis=300000
spring.read.datasource.validationQuery=SELECT 'x'
spring.read.datasource.testWhileIdle=true
spring.read.datasource.testOnBorrow=false
spring.read.datasource.testOnReturn=false
spring.read.datasource.poolPreparedStatements=false
spring.read.datasource.maxOpenPreparedStatements=20
spring.read.datasource.slowSqlMillis=5000
spring.read.datasource.isLogSlowSql=true
