spring.config.name=fossa-web
spring.main.show-banner=false

# ??????
server.port=8080
server.servlet.context-path=/fossa
server.servlet.session.timeout=1800s

# Tomcat ??
server.tomcat.basedir=/data/tomcat-base
server.tomcat.uri-encoding=UTF-8

# HTTP ????????
http.client.socketTimeout=10
http.client.connectionRequestTimeout=10
http.client.connectionTimeout=10
http.client.closeIdleConnections=30

# Thymeleaf
spring.thymeleaf.prefix=/WEB-INF/web/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html
spring.thymeleaf.cache=true


# ???????
wechat.appid=wx95ab971ffe17590e
wechat.secret=b5c316445a61594e7ce394311d8d930b
wechat.grant-type=authorization_code

mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.fossa.entity
# ???????????????? resultMap
mybatis.configuration.map-underscore-to-camel-case=true


upload.image.path=/data/upload
upload.image.domain=https://yuni.fossa.top

huita.cors.origins=https://yuni.fossa.top